# Generated by Django 4.2.7 on 2023-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expeted_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
